
#-----Stage 1 ---Build Stage
FROM node:22-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# ---Stage 2 --Production stage
FROM  node:22-slim
WORKDIR /app
COPY --from=builder /app /app
EXPOSE 5173
CMD [ "npm","run","dev" ]




